CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3

CREATE TABLE IF NOT EXISTS `mydb`.`control_table` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ITEM_TYPE` VARCHAR(45) NOT NULL,
  `BATCH_NUMBER` INT NOT NULL,
  `UPDATE_TS` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `INDEX_2` (`ITEM_TYPE` ASC) VISIBLE,
  INDEX `INDEX_1` (`ITEM_TYPE` ASC, `BATCH_NUMBER` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3

CREATE TABLE IF NOT EXISTS `mydb`.`item` (
  `ITEM_ID` INT NOT NULL AUTO_INCREMENT,
  `ITEM_TYPE` VARCHAR(45) NOT NULL,
  `ITEM_BATCH` INT NOT NULL,
  `ITEM_DATA` VARCHAR(45) NOT NULL,
  `ITEM_EXECUTOR` VARCHAR(45) NOT NULL,
  `ITEM_STATUS` VARCHAR(45) NOT NULL DEFAULT 'PENDING',
  `crete_ts` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_ts` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ITEM_ID`),
  UNIQUE INDEX `UNIQUE_ITEM_IDX` (`ITEM_TYPE` ASC, `ITEM_DATA` ASC) COMMENT '\'COMBNATION OF ITEM_TYPE + ITEM_DATA IS UNIQUE\'' INVISIBLE,
  INDEX `ITEM_STATUS_IDX` (`ITEM_TYPE` ASC, `ITEM_STATUS` ASC) COMMENT '\'MOST FREQUENTLY USED QUERY\'' VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3